# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_vgg9_new_curv0.9_def7/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_vgg9_new_curv0.9_def7/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_vgg9_new_curv0.9_def7/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_vgg9_new_curv0.9_def7/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_nonorm_newcurv_no1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_nonorm_newcurv_no1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori100_vgg9_new_curv_lr2/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarwd100_vgg9_new_curv1/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarwd100_vgg9_new_curv1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarwd100_vgg9_new_curv1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarwd100_vgg9_new_curv1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori100_vgg9_new_curv1/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori100_vgg9_new_curv1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori100_vgg9_new_curv1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori100_vgg9_new_curv1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_combinemag_time1/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_combinemag_time1/ --alpha 0.9
python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_sinkhorn/ --dataset cifar --community 1 --edge 0 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_sinkhorn/ --alpha 0.5
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_vgg9_new_curv_s2/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_vgg9_new_curv_s2/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarori_nonorm_newcurv_add1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarori_nonorm_newcurv_add1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifaradv_nonorm_newcurv_add1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifaradv_nonorm_newcurv_add1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/cnn/ --mnist_res_path res/w4/relu/cifarwd_nonorm_newcurv_add1/ --dataset cifar --community 0 --edge 1 --activation relu --sample_num 1 --mnist_data_path res/w4/relu/cifarwd_nonorm_newcurv_add1/ --alpha 0.9
