# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnori_nonorm_newcurv1/ --dataset mnist --community 1 --edge 0 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnori_nonorm_newcurv1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnwd_norm_newcurv/ --dataset mnist --community 1 --edge 0 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnwd_norm_newcurv/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnadv_nonorm_newcurv/ --dataset mnist --community 1 --edge 0 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnadv_nonorm_newcurv/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnori_nonorm_newcurv_add1/ --dataset mnist --community 0 --edge 1 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnori_nonorm_newcurv_add1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnwd_nonorm_newcurv_add1/ --dataset mnist --community 0 --edge 1 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnwd_nonorm_newcurv_add1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/new/ --mnist_res_path res/w4/relu/cnnadv_nonorm_newcurv_add1/ --dataset mnist --community 0 --edge 1 --activation relu --sample_num 10 --mnist_data_path res/w4/relu/cnnadv_nonorm_newcurv_add1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnori_nonorm_newcurv_d_no1/ --dataset mnist --community 1 --edge 0 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnori_nonorm_newcurv_d_no1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnwd_nonorm_newcurv_d_no1/ --dataset mnist --community 1 --edge 0 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnwd_nonorm_newcurv_d_no1/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnadv_nonorm_newcurv_d_no1/ --dataset mnist --community 1 --edge 0 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnadv_nonorm_newcurv_d_no1/ --alpha 0.9
python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnori_nonorm_newcurv_d/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnori_nonorm_newcurv_d/ --alpha 0.9
python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnwd_nonorm_newcurv_d/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnwd_nonorm_newcurv_d/ --alpha 0.9
python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnadv_nonorm_newcurv_d/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnadv_nonorm_newcurv_d/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name ori --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnori_nonorm_newcurv/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnori_nonorm_newcurv/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name wd --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnwd_nonorm_newcurv/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnwd_nonorm_newcurv/ --alpha 0.9
# python removal.py --lidar 0 --image 1 --cifar small --metric w4 --model_type cnn --model_name adv --model_path CNN/models/new/ --mnist_res_path res/w4/tanh/cnnadv_nonorm_newcurv/ --dataset mnist --community 0 --edge 1 --activation tanh --sample_num 10 --mnist_data_path res/w4/tanh/cnnadv_nonorm_newcurv/ --alpha 0.9